### ISSUE TITLE
Could not establish connection to OSX. Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

### ISSUE THREAD

**Issue by csalvato** [jnovack/docker-vscode-hack-osx#1]
Hi there!

Thanks so much for creating this workaround.

When I try to set this up, I am getting the following error: 

> Could not establish connection to XXX. Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

This is what I have in my ssh config being used by VS Code:

```
Host OSX
  HostName 192.168.0.XX
  User root
  Port 2222
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
```

It seems like this script is set up to not as for a password, but I also have no keys install.  Is that a problem?  If not, any other advice? What am I missing?

**Comment by jnovack** [comment]
By default, it's set up for password.  The password by default is in the `Dockerfile`

```
RUN echo 'root:DanielSmithRocks' | chpasswd
```

You may wish to download this, change the password in the `Dockerfile` and rebuild.

**Comment by jnovack** [comment]
closing this issue because the official upstream image has a PR accepted and official work-around posted.

Work-around until mainstream:
1. Download [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. Then search extension `Remote - SSH (Nightly)`
